from pathlib import Path

here = Path(__file__).parent.absolute()
version_major, version_minor, version_patch = (here / "VERSION").read_text().split(".")


version_header = here / "includes" / "version.hpp"
version_header.write_text(
f"""
// This file is generated by version.py
#pragma once

#define STRONGER_CPP_VERSION_MAJOR {version_major}
#define STRONGER_CPP_VERSION_MINOR {version_minor}
#define STRONGER_CPP_VERSION_PATCH {version_patch}
""".lstrip("\n")
    )